// <auto-generated />
using System;
using DailyNews.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyNews.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20260205102242_AddSeedDataFixed")]
    partial class AddSeedDataFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("DailyNews.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "دانشجوی کامپیوتر ورودی ۱۴۰۰ - توسعه‌دهنده اصلی",
                            Name = "حسین جعفری شارمی"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "دانشجوی کامپیوتر ورودی ۱۳۹۸ - مدیر پروژه",
                            Name = "معین آقائی کوهی"
                        });
                });

            modelBuilder.Entity("DailyNews.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "سیاسی"
                        },
                        new
                        {
                            Id = 2,
                            Name = "اقتصادی"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ورزشی"
                        },
                        new
                        {
                            Id = 4,
                            Name = "فرهنگی"
                        });
                });

            modelBuilder.Entity("DailyNews.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            Content = "در تازه‌ترین اخبار سیاسی...",
                            PublishDate = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "تحولات جدید سیاسی کشور"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 2,
                            Content = "دلار به رکورد جدیدی رسید...",
                            PublishDate = new DateTime(2026, 2, 3, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "افزایش نرخ ارز در بازار"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            CategoryId = 3,
                            Content = "بازیکنان درخشیدند...",
                            PublishDate = new DateTime(2026, 2, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "پیروزی تیم ملی در بازی دوستانه"
                        });
                });

            modelBuilder.Entity("DailyNews.Models.News", b =>
                {
                    b.HasOne("DailyNews.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyNews.Models.Category", "Category")
                        .WithMany("News")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DailyNews.Models.Category", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
